apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: sirijangam/sirirepo:latest
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_CONN_STR
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials
              key: MONGO_CONN_STR
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials
              key: MONGO_USERNAME
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials
              key: MONGO_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
